name: Video Creator
on: workflow_call

jobs:
    create_video:
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
        runs-on: ubuntu-latest
        steps:
            - run: export "$OPENAI_API_KEY"
            - uses: "actions/checkout@main"
              with:
                repository: "ridgeway-warrior/video-maker"
            - uses: "actions/setup-node@main"
            - uses: "pnpm/action-setup@master"
              with: 
                version: 11
            - run: pnpm ci
            - run: pnpm remotion render MyComp video.mp4
            - uses: "actions/upload-artifact@main"
              with:
                name: remotion-video
                path: video.mp4

